[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitm-1     ; sometimes better match for mini style
framework = arduino
board_build.flash_size = 4MB
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D USER_SETUP_LOADED=1
    -include include/User_Setup.h
    -DLV_CONF_INCLUDE_SIMPLE 
    -I include

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    Bodmer/TFT_eSPI
    lvgl/lvgl
